#include<stdio.h>
/*welcome to kbc*/
void main()
{
char ansa,ansb,ansc,ansd,anse,ansf,ansg,ansh,ansi,ansj,ansk,ansl,ansm,ansn,anso,A,B,C,D,K;
printf("WELCOME TO MY SHOW KBC AND IM YOUR HOST AMITABH BACHCHAN\n THIS IS A MONEY GAME SHOW WHERE THE CONTESTENTS PLAY AND WE PAY\n THERE ARE GOING TO BE 15 QUESTIONS\n");
printf("THE TOTAL WINNING AMOUNT OF THIS SHOW IS 1 CRORE\n");
printf("SO HERE WE GO WITH THE FIRST QUESTION\n");
printf("WHERE IS THE WORLDS TALLEST BUILDING LOCATED?\n A.DUBAI\n B.MUMBAI\n C.NEW YORK\n D.ADELIDE\n");
scanf("%c",&ansa);

if(ansa!='A')
printf("YOU ARE WRONG AND YOU HAVE WON 0 RUPPEES\n");

else
{
printf("YOU ARE CORRECT... YOUR TOTAL WINNING AMOUNT IS 1000 RUPPEES\n");

printf("SECOND QUESTION ON YOUR SCREEN\n");
printf("WHICH COUNTRY WON THE ICC CRICKET WORLD CUP 2015?\n A.SOUTH AFRICA\n B.AUSTRALIA\n C.INDIA\n D.PAKISTAN\n");
scanf("%c",&K);
scanf("%c",&ansb);
if(ansb!='B')
printf("YOU ARE WRONG AND YOUR TOTAL WINNING AMOUNT IS 1000 RUPPEES\n");

else
{
printf("YOU ARE CORRECT... YOU PROCEED TO THE NEXT QUESTION. YOUR TOTAL WINNING AMOUNT IS 2000 RUPPEES\n");

printf("THIRD QUESTION ON YOUR SCREEN\n");
printf("WHICH THE CURRENT FINANCE MINISTER OF INDIA?\n A.SUSHMA SWARAJ\n B.ARUN JAITLEY\n C.AMIT SHAH\n D.PIYUSH GOYAL\n");
scanf("%c",&K);
scanf("%c",&ansc);
if(ansc!='B')
printf("YOU ARE ELIMINATED AND YOUR TOTAL WINNING AMOUNT IS 2000 RUPPEES\n");

else
{
printf("YOU ARE CORRECT. YOUR WINNING AMOUNT IS 5000 RUPPEES\n");

printf("FOURTH QUESTION ON YOUR SCREEN\n");
printf("WHEN DID THE FAMOUS JALLIANWALAHBAGH MASSACRE TAKE PLACE?\n A.1923\n B.1910\n C.1911\n D.1919\n");
scanf("%c",&K);
scanf("%c",&ansd);
if(ansd!='D')
printf("YOU ARE INCORRECT AND YOUR TOTAL WINNING AMOUNT IS 5000 RUPPES\n");

else
{
printf("YOU ARE CORRECT... YOU HAVE BEEN PLAYING AMAZINGLY AND YOUR WINNING AMOUNT IS 8000 RUPPEES\n");

printf("FIFTH QUESTION ON YOUR SCREEN NOW\n");
printf("WHO AMONG THESE HAS WON A NOBEL PRIZE?\n A.NARENDRA MODI\n B.MAHATMA GANDHI\n C.BARACK OBAMA\n D.SACHIN TENDULKAR\n");
scanf("%c",&K);
scanf("%c",&anse);
if(anse!='C')
printf("YOU ARE WRONG AND YOU HAVE WON 8000 RUPPEES\n");

else
{
printf("YOU ARE CORRECT AND YOUR WINNING AMOUNT IS 10000 RUPPEES\n");

printf("SIXTH QUESTION ON YOUR SCREEN FOR 20000 RUPPEES\n");
printf("WHAT IS THE MAIN RIVER FLOWING IN ENGLAND?\n A.THAMES\n B.TSANGPO\n C.NILE\n D.AMAZON\n");
scanf("%c",&K);
scanf("%c",&ansf);
if(ansf!='A')
printf("YOU ARE INCORRECT AND YOU HAVE WON 10k RUPPEES\n");

else
{
printf("YOU ARE CORRECT SO YOU HAVE WON 20k RUPPEES\n");

printf("SEVENTH QUESTION 40k RUPPEES AND YOUR SCREEN NOW\n");
printf("WHO HAS BEEN ADDED IN THE TOP 10 RICHEST SPORTSPERSON CURRENTLY?\n A.MS DHONI\n B.PV SINDHU\n C.MAHESH BHUPATI\n D.VIRAT KOHLI\n");
scanf("%c",&K);
scanf("%c",&ansg);
if(ansh!='D')
printf("YOU ARE INCORRECT AND YOU HAVE WON 20K RUPPEES... YOU HAVE BEEN ELIMINATED\n");

else
{
printf("CONGRATULATIONS YOU ARE CORRECT SO YOUR TOTAL WINNING AMOUNT IS 40k RUPPEES\n");

printf("EIGHTH QUESTION COMING UP NOW\n");
printf("WHO IS THE WRITER OF THE BOOK THE STORY OF MY LIFE?\n A.CHARLES DICKENS\n B.HELEN KELLER\n C.RUDYAD KIPLING\n D.ERNEST HACKEL\n");
scanf("%c",&K);
scanf("%c",&ansh);
if(ansh!='B')
printf("YOU ARE WRONG SORRY YOUR TOTAL WINNING AMOUNT IS 40K RUPPEES\n");

else
{
printf("YOU ARE CORRECT WE ARE HAPPY TO INFORM YOU THAT YOU HAVE BEEN ELIMINATED SO YOUR WINNING AMOUNT IS 80K RUPPEES?\n");

printf("NINTH QUESTION NOW FOR 1 LAC RUPPEES ON YOUR SCREEN NOW\n");
printf("WHERE IS KAZAN LOCATED?\n A.KAZAKHISTAN\n B.CHINA\n C.CROATIA\n D.RUSSIA\n");
scanf("%c",&K);
scanf("%c",&ansi);
if(ansi!='D')
printf("SORRY YOU ARE WRONG AND YOU HAVE WON 80K RUPPEES\n");

else
{
printf("YOU HAVE GIVE A RIGHT ANSWER... YOUR WINNING AMOUNT IS 1 LAC RUPPEES\n");

printf("NEXT QUESTION ON YOUR SCREEN FOR 2 LACS\n");
printf("WHICH OF THE FOLLOWING HAS AN ACIDIC NATURE\n A.NAOH\n B.NAHCO3\n C.H20\n D.HCL\n");
scanf("%c",&K);
scanf("%c",&ansj);
if(ansj!='D')
printf("SORRY YOU ARE WRONG AND YOUR TOTAL WINNING PRICE IS 1 LAC RUPPEES\n");

else
{
printf("YOU ARE PLAYING WELL IN THIS GAME AND YOUR WINNING PRIZE MONEY IS 2 LAC RUPPEES\n");

printf("LETS PROCEED TO QUESTION 11 FOR 4 LAC RUPPEES\n");
printf("WHO RULED THE NAZI PARTY?\n A.ADOLF HITLOR\n B.NAPOLEON BONAPARTE\n C.VASCO DE GAMA\n D.MK GANDHI\n");
scanf("%c",&K);
scanf("%c",&ansk);
if(ansk!='A')
printf("YOU ARE INCORRECT AND YOUR TOTAL WINNING AMOUNT IS 2 LAC RUPPEES\n");

else
{
printf("YOU HAVE WON 4 LAC RUPPEES\n");

printf("NEXT QUESTION FOR 10  LAC RUPPEES ON YOUR SCREEN NOW\n");
printf("WHO WAS THE LAST EMPEROR OF THE MUGHAL EMPIRE?\n A. BABUR\n B.BAHADUR SHAH\n  C.HUMAYUN\n D.AKBAR\n");
scanf("%c",&K);
scanf("%c",&ansl);
if(ansl!='B')
printf("SORRY YOU ARE WRONG... YOUR TOTAL WINNING AMOUNT IS 4 LACS\n");

else
{
printf("YOUR ANSWER IS CORRECT SO YOU HAVE WON 10 LACS CONGRATULATIONS\n");

printf("13TH QUESTION COMING UP FOR 50 LAC RUPPEES\n");
printf("WHO IS THE FATHER OF COMPUTERS\n A.CHARLES BABBAGE\n B.BILL GATES\n C.HEBERT BAKER\n D.NONE OF THESE\n");
scanf("%c",&K);
scanf("%c",&ansm);
if(ansm!='A')
printf("YOU HAVE WON 10 LAC RUPPEES WELL PLAYED LAD\n");

else
{
printf("YOU ARE CORRECT WELL PLAYED BUDDY YOUR TOTAL WINNING AMOUNT IS 50 LACS\n");

printf("QUESTION 14 FOR 75 LAC RUPPEES ON YOUR SCREEN NOW\n");
printf("WHICH MOSQUITOE CAUSES DENGUE?\n A.FEMALE ADES\n B.MALE ADES\n C.FEMALE ANOPHELES\n D.MALE ANOPHELES\n");
scanf("%c",&K);
scanf("%c",&ansn);
if(ansn!='A')
printf("YOU HAVE BEEN ELIMINATED SORRY\n");

else
{
printf("YOU ARE CORRECT SO YOU HAVE WON 75 LACS SO WELL PLAYED\n");

printf("FINAL QUESTION ON YOUR SCREEN NOW");
printf("WHO IS THE CURRENT CEO OF APPLE?\n A.SUNDER PICHAI\n B.TIM COOK\n C.JEFF BEZOS\n D.SATYA NADELLA\n");
scanf("%c",&K);
scanf("%c",&anso);
if(anso!='B')
printf("SORRY YOU COULDNT BECOME A CROREPATI SO YOUR TOTAL WINNING AMOUNT IS 75 LACS WELL PLAYED\n");

else
{
printf("YOU WON IT.CONGRATULATIONS YOU HAVE BECOME A CROREPATI. YOUR WINNING AMOUNT IS 1 CRORE RUPPEES WELL PLAYED");
}}}}}}}}}}}}}}}}




